FROM python:3
WORKDIR /app
COPY requirements.txt /app

RUN pip install -r requirements.txt
ENV GOOGLE_APPLICATION_CREDENTIALS /tmp/credentials/credentials.json
ENV RAW_BUCKET fpl-japan-rawfiles
COPY *.py /app
ENTRYPOINT ["python", "element.py"]
